2023-07-25 18:28:52 | ERROR | 'ObjectData' object has no attribute 'to_json'
2023-07-25 18:28:52 | ERROR | Traceback (most recent call last):
  File "/var/www/html/demoApiV1/src/services/ObjectDataServices.py", line 22, in get_data
    objectsData.append(objectData.to_json())
AttributeError: 'ObjectData' object has no attribute 'to_json'

2023-07-25 18:56:21 | ERROR | No module named 'xlsxwriter'
2023-07-25 18:56:21 | ERROR | Traceback (most recent call last):
  File "/var/www/html/demoApiV1/src/routes/ObjectDataRoutes.py", line 38, in getObjectData
    writer = pd.ExcelWriter(f'{filename_excel}', engine='xlsxwriter')
  File "/var/www/html/demoApiV1/env/lib/python3.10/site-packages/pandas/io/excel/_xlsxwriter.py", line 192, in __init__
    from xlsxwriter import Workbook
ModuleNotFoundError: No module named 'xlsxwriter'

2023-07-25 18:59:28 | ERROR | 'XlsxWriter' object has no attribute 'save'
2023-07-25 18:59:28 | ERROR | Traceback (most recent call last):
  File "/var/www/html/demoApiV1/src/routes/ObjectDataRoutes.py", line 47, in getObjectData
    writer.save()
AttributeError: 'XlsxWriter' object has no attribute 'save'

2023-07-25 19:37:56 | ERROR | 'XlsxWriter' object has no attribute 'save'
2023-07-25 19:37:56 | ERROR | Traceback (most recent call last):
  File "/var/www/html/demoApiV1/src/routes/ObjectDataRoutes.py", line 54, in getObjectData
    writer.save()
AttributeError: 'XlsxWriter' object has no attribute 'save'

2023-07-25 19:47:29 | ERROR | File is not a zip file
2023-07-25 19:47:29 | ERROR | Traceback (most recent call last):
  File "/var/www/html/demoApiV1/src/routes/ObjectDataRoutes.py", line 57, in getObjectData
    workbook = openpyxl.load_workbook(filename=filename_excel)
  File "/var/www/html/demoApiV1/env/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 344, in load_workbook
    reader = ExcelReader(filename, read_only, keep_vba,
  File "/var/www/html/demoApiV1/env/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 123, in __init__
    self.archive = _validate_archive(fn)
  File "/var/www/html/demoApiV1/env/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 95, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "/usr/lib/python3.10/zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

2023-07-25 19:52:19 | ERROR | 'DataFrame' object has no attribute 'append'
2023-07-25 19:52:19 | ERROR | Traceback (most recent call last):
  File "/var/www/html/demoApiV1/src/routes/ObjectDataRoutes.py", line 41, in getObjectData
    dfHeadData = dfHeadData.append({
  File "/var/www/html/demoApiV1/env/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

2023-07-25 20:04:15 | ERROR | 'dict' object has no attribute 'dt_server'
2023-07-25 20:04:15 | ERROR | Traceback (most recent call last):
  File "/var/www/html/demoApiV1/src/routes/ObjectDataRoutes.py", line 64, in getObjectData
    sheetData[f'A{cont}'] = element.dt_server
AttributeError: 'dict' object has no attribute 'dt_server'

2023-07-28 15:53:04 | ERROR | No module named 'xlsxwriter'
2023-07-28 15:53:04 | ERROR | Traceback (most recent call last):
  File "/var/www/html/python-api-stech/src/routes/ObjectDataRoutes.py", line 54, in getObjectData
    writer = pd.ExcelWriter(f'{filename_excel}', engine='xlsxwriter')
  File "/var/www/html/python-api-stech/env/lib/python3.10/site-packages/pandas/io/excel/_xlsxwriter.py", line 192, in __init__
    from xlsxwriter import Workbook
ModuleNotFoundError: No module named 'xlsxwriter'

2023-07-28 15:53:18 | ERROR | No module named 'xlsxwriter'
2023-07-28 15:53:18 | ERROR | Traceback (most recent call last):
  File "/var/www/html/python-api-stech/src/routes/ObjectDataRoutes.py", line 54, in getObjectData
    writer = pd.ExcelWriter(f'{filename_excel}', engine='xlsxwriter')
  File "/var/www/html/python-api-stech/env/lib/python3.10/site-packages/pandas/io/excel/_xlsxwriter.py", line 192, in __init__
    from xlsxwriter import Workbook
ModuleNotFoundError: No module named 'xlsxwriter'

2023-07-28 15:53:41 | ERROR | No module named 'xlsxwriter'
2023-07-28 15:53:41 | ERROR | Traceback (most recent call last):
  File "/var/www/html/python-api-stech/src/routes/ObjectDataRoutes.py", line 54, in getObjectData
    writer = pd.ExcelWriter(f'{filename_excel}', engine='xlsxwriter')
  File "/var/www/html/python-api-stech/env/lib/python3.10/site-packages/pandas/io/excel/_xlsxwriter.py", line 192, in __init__
    from xlsxwriter import Workbook
ModuleNotFoundError: No module named 'xlsxwriter'

2023-07-28 16:14:34 | ERROR | Notification.__init__() takes 11 positional arguments but 12 were given
2023-07-28 16:14:34 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\services\NotificationServices.py", line 35, in getAllNotificationUser
    objectData = Notification(
                 ^^^^^^^^^^^^^
TypeError: Notification.__init__() takes 11 positional arguments but 12 were given

2023-07-28 16:15:03 | ERROR | Notification.__init__() takes 11 positional arguments but 12 were given
2023-07-28 16:15:03 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\services\NotificationServices.py", line 35, in getAllNotificationUser
    objectData = Notification(
                 ^^^^^^^^^^^^^
TypeError: Notification.__init__() takes 11 positional arguments but 12 were given

2023-07-28 16:20:26 | ERROR | Notification.__init__() missing 8 required positional arguments: 'fecha_actualizada', 'detalle', 'leida', 'oculta', 'tipo', 'imei_vehiculo', 'identificador_tipo', and 'contador_reenvios'
2023-07-28 16:20:26 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\services\NotificationServices.py", line 35, in getAllNotificationUser
    objectData = Notification(
                 ^^^^^^^^^^^^^
TypeError: Notification.__init__() missing 8 required positional arguments: 'fecha_actualizada', 'detalle', 'leida', 'oculta', 'tipo', 'imei_vehiculo', 'identificador_tipo', and 'contador_reenvios'

2023-07-28 16:28:42 | ERROR | strptime() argument 1 must be str, not datetime.datetime
2023-07-28 16:28:42 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\services\NotificationServices.py", line 43, in getAllNotificationUser
    , datetime.strptime(row[2], "%Y-%m-%dT%H:%M:%S.%fZ")
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not datetime.datetime

2023-07-28 16:29:46 | ERROR | Notification.__init__() missing 8 required positional arguments: 'fecha_actualizada', 'detalle', 'leida', 'oculta', 'tipo', 'imei_vehiculo', 'identificador_tipo', and 'contador_reenvios'
2023-07-28 16:29:46 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\services\NotificationServices.py", line 35, in getAllNotificationUser
    objectData = Notification(
                 ^^^^^^^^^^^^^
TypeError: Notification.__init__() missing 8 required positional arguments: 'fecha_actualizada', 'detalle', 'leida', 'oculta', 'tipo', 'imei_vehiculo', 'identificador_tipo', and 'contador_reenvios'

2023-07-28 16:47:20 | ERROR | 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2023-07-28 16:47:20 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\NotificationRoutes.py", line 20, in notiSelec
    data = request.get_json()
           ^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\wrappers\request.py", line 611, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\wrappers\request.py", line 654, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

2023-07-28 16:49:36 | ERROR | 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2023-07-28 16:49:36 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\NotificationRoutes.py", line 20, in notiSelec
    data = request.get_json()
           ^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\wrappers\request.py", line 611, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\wrappers\request.py", line 654, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

2023-07-28 16:49:42 | ERROR | 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2023-07-28 16:49:42 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\NotificationRoutes.py", line 20, in notiSelec
    data = request.get_json()
           ^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\wrappers\request.py", line 611, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\wrappers\request.py", line 654, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

