
2023-08-09 10:22:30 | ERROR | 'int' object has no attribute 'is_active'
2023-08-09 10:22:30 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 18, in swagger_oauth
    login_user(is_authenticated[0][0])
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask_login\utils.py", line 180, in login_user
    if not force and not user.is_active:
                         ^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'is_active'

2023-08-09 10:25:27 | ERROR | 'int' object has no attribute 'is_active'
2023-08-09 10:25:27 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 18, in swagger_oauth
    login_user(is_authenticated[0][0])
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask_login\utils.py", line 180, in login_user
    if not force and not user.is_active:
                         ^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'is_active'

2023-08-09 10:48:20 | ERROR | tuple indices must be integers or slices, not str
2023-08-09 10:48:20 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\services\AuthSwaggerServices.py", line 39, in get_user_by_id
    user = User(result['id'], result['username'], result['password'])
                ~~~~~~^^^^^^
TypeError: tuple indices must be integers or slices, not str

2023-08-09 11:20:04 | ERROR | Could not build url for endpoint 'main_mainSwaggerOauth.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_oauth' instead?
2023-08-09 11:20:04 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 37, in swagger_oauth
    return redirect(url_for('main_mainSwaggerOauth.swagger_page'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main_mainSwaggerOauth.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_oauth' instead?

2023-08-09 11:42:44 | ERROR | Could not build url for endpoint 'main_mainSwaggerOauth.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_oauth' instead?
2023-08-09 11:42:44 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 37, in swagger_oauth
    return redirect(url_for('main_mainSwaggerOauth.swagger_page'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main_mainSwaggerOauth.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_oauth' instead?

2023-08-09 11:44:27 | ERROR | Could not build url for endpoint 'main_mainSwaggerOauth.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_oauth' instead?
2023-08-09 11:56:00 | ERROR | Could not build url for endpoint 'main_mainSwaggerOauth.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_oauth' instead?
2023-08-09 11:56:00 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 23, in swagger_oauth
    return redirect(url_for('main_mainSwaggerOauth.swagger_page'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main_mainSwaggerOauth.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_oauth' instead?

2023-08-09 12:03:58 | ERROR | Could not build url for endpoint 'main_mainSwaggerOauth.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_oauth' instead?
2023-08-09 12:03:58 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 38, in swagger_oauth
    return redirect(url_for('main_mainSwaggerOauth.swagger_page'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main_mainSwaggerOauth.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_oauth' instead?

2023-08-09 12:07:45 | ERROR | Could not build url for endpoint 'swagger_blueprint.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_oauth' instead?
2023-08-09 12:07:45 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 37, in swagger_oauth
    return redirect(url_for('swagger_blueprint.swagger_page'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'swagger_blueprint.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_oauth' instead?

2023-08-09 12:09:02 | ERROR | Could not build url for endpoint 'swagger_blueprint.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_oauth' instead?
2023-08-09 12:09:02 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 37, in swagger_oauth
    return redirect(url_for('swagger_blueprint.swagger_page'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'swagger_blueprint.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_oauth' instead?

2023-08-09 12:11:55 | ERROR | Could not build url for endpoint 'swagger_blueprint.redirect_to_swagger'. Did you mean 'main_mainSwaggerOauth.login_page' instead?
2023-08-09 12:11:55 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 37, in swagger_oauth
    return redirect(url_for('swagger_blueprint.redirect_to_swagger'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'swagger_blueprint.redirect_to_swagger'. Did you mean 'main_mainSwaggerOauth.login_page' instead?

2023-08-09 12:14:29 | ERROR | Could not build url for endpoint 'swagger_blueprint.redirect_to_swagger'. Did you mean 'main_mainSwaggerOauth.login_page' instead?
2023-08-09 12:14:29 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 41, in swagger_oauth
    return redirect(url_for('swagger_blueprint.redirect_to_swagger'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'swagger_blueprint.redirect_to_swagger'. Did you mean 'main_mainSwaggerOauth.login_page' instead?

2023-08-09 12:16:11 | ERROR | Could not build url for endpoint 'swagger_blueprint.redirect_to_swagger'. Did you mean 'main_userSelect.userSelect' instead?
2023-08-09 12:16:11 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 41, in swagger_oauth
    return redirect(url_for('swagger_blueprint.redirect_to_swagger'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'swagger_blueprint.redirect_to_swagger'. Did you mean 'main_userSelect.userSelect' instead?

2023-08-09 12:22:58 | ERROR | Could not build url for endpoint 'swagger_blueprint.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_oauth' instead?
2023-08-09 12:22:58 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 38, in swagger_oauth
    return redirect(url_for('swagger_blueprint.swagger_page'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'swagger_blueprint.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_oauth' instead?

2023-08-09 12:24:10 | ERROR | Could not build url for endpoint 'swagger_blueprint.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_page' instead?
2023-08-09 12:24:10 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 38, in swagger_oauth
    return redirect(url_for('swagger_blueprint.swagger_page'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'swagger_blueprint.swagger_page'. Did you mean 'main_mainSwaggerOauth.swagger_page' instead?

2023-08-09 15:22:15 | ERROR | 'username'
2023-08-09 15:22:15 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 35, in swagger_oauth
    is_authenticated = AuthSwaggerServices.loginSwagger(data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\apps\python-api-stech\src\services\AuthSwaggerServices.py", line 16, in loginSwagger
    username = data['username']
               ~~~~^^^^^^^^^^^^
KeyError: 'username'

2023-08-09 15:23:10 | ERROR | 'username'
2023-08-09 15:23:10 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 35, in swagger_oauth
    is_authenticated = AuthSwaggerServices.loginSwagger(data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\apps\python-api-stech\src\services\AuthSwaggerServices.py", line 16, in loginSwagger
    username = data['username']
               ~~~~^^^^^^^^^^^^
KeyError: 'username'

2023-08-09 15:24:45 | ERROR | 'username'
2023-08-09 15:24:45 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 35, in swagger_oauth
    is_authenticated = AuthSwaggerServices.loginSwagger(data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\apps\python-api-stech\src\services\AuthSwaggerServices.py", line 16, in loginSwagger
    username = data['username']
               ~~~~^^^^^^^^^^^^
KeyError: 'username'

2023-08-09 15:26:19 | ERROR | 'username'
2023-08-09 15:26:19 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\AuthSwagger.py", line 35, in swagger_oauth
    is_authenticated = AuthSwaggerServices.loginSwagger(data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\apps\python-api-stech\src\services\AuthSwaggerServices.py", line 16, in loginSwagger
    username = data['username']
               ~~~~^^^^^^^^^^^^
KeyError: 'username'

2023-08-10 12:25:13 | ERROR | 'id'
2023-08-10 12:25:13 | ERROR | Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\routes\NotificationRoutes.py", line 307, in notiRead
    NotificationService.uploadNotiRead(data['id'])
                                       ~~~~^^^^^^
KeyError: 'id'

2023-08-22 00:58:19 | ERROR | (2006, "MySQL server has gone away (ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None))")
2023-08-22 00:58:19 | ERROR | Traceback (most recent call last):
  File "c:\apps\python-api-stech\env\Lib\site-packages\pymysql\connections.py", line 760, in _write_bytes
    self._sock.sendall(data)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\apps\python-api-stech\src\services\NotificationServices.py", line 380, in uploadNotiRead
    cursor.execute(f"""
  File "c:\apps\python-api-stech\env\Lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "c:\apps\python-api-stech\env\Lib\site-packages\pymysql\cursors.py", line 325, in _query
    conn.query(q)
  File "c:\apps\python-api-stech\env\Lib\site-packages\pymysql\connections.py", line 548, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "c:\apps\python-api-stech\env\Lib\site-packages\pymysql\connections.py", line 818, in _execute_command
    self._write_bytes(packet)
  File "c:\apps\python-api-stech\env\Lib\site-packages\pymysql\connections.py", line 763, in _write_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None))")

